package com.hzhetun.example.mapper;

import com.hzhetun.example.pojo.SystemSmsApi;
import org.springframework.stereotype.Repository;

/**
 * @author cbk
 * @date 2017/12/23
 */
@Repository
public interface SystemSmsApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_sms_api
     *
     * @mbg.generated
     * @param id
     * @return int
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_sms_api
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int insert(SystemSmsApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_sms_api
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int insertSelective(SystemSmsApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_sms_api
     *
     * @mbg.generated
     * @param id
     * @return SystemSmsApi
     */
    SystemSmsApi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_sms_api
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKeySelective(SystemSmsApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_sms_api
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKey(SystemSmsApi record);

    /**
     * 根据短信api名称查询的方法
     * @param apiName
     * @return SystemSmsApi
     */
    SystemSmsApi findByApiName(String apiName);
}