package com.hzhetun.example.mapper;

import com.hzhetun.example.pojo.SystemFile;
import org.springframework.stereotype.Repository;

/**
 * file mapper interface
 * @author cbk
 * @date 2017/12/23
 */

@Repository
public interface SystemFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbg.generated
     * @param id
     * @return int
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int insert(SystemFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int insertSelective(SystemFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbg.generated
     * @param id
     * @return SystemFile
     */
    SystemFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKeySelective(SystemFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_file
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKey(SystemFile record);
}