package cn.admin.file.pojo;

/**
 * @author cbk
 * @date 2017/12/23
 */
public class SystemIcon{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_icon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_icon.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_icon.unicode
     *
     * @mbg.generated
     */
    private String unicode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_icon.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_icon.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_icon.id
     *
     * @return the value of system_icon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_icon.id
     *
     * @param id the value for system_icon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_icon.name
     *
     * @return the value of system_icon.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_icon.name
     *
     * @param name the value for system_icon.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_icon.unicode
     *
     * @return the value of system_icon.unicode
     *
     * @mbg.generated
     */
    public String getUnicode() {
        return unicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_icon.unicode
     *
     * @param unicode the value for system_icon.unicode
     *
     * @mbg.generated
     */
    public void setUnicode(String unicode) {
        this.unicode = unicode == null ? null : unicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_icon.comment
     *
     * @return the value of system_icon.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_icon.comment
     *
     * @param comment the value for system_icon.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_icon.weight
     *
     * @return the value of system_icon.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_icon.weight
     *
     * @param weight the value for system_icon.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}