package com.hzhetun.example.mapper;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.hzhetun.example.pojo.SystemRole;
import org.springframework.stereotype.Repository;

/**
 * @author cbk
 * @date 2017/12/23
 */
@Repository
public interface SystemRoleMapper extends BaseMapper<SystemRole>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated
     * @param id
     * @return int
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated
     */
//    int insert(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int insertSelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated
     * @param id
     * @return SystemRole
     */
    SystemRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKeySelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_role
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKey(SystemRole record);
}