package cn.admin.file.mapper;

import cn.admin.file.pojo.SystemIcon;
import com.baomidou.mybatisplus.mapper.BaseMapper;
import org.springframework.stereotype.Repository;

/**
 * @author cbk
 * @date 2017/12/23
 */
@Repository
public interface SystemIconMapper extends BaseMapper<SystemIcon> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_icon
     *
     * @mbg.generated
     * @param id
     * @return int
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_icon
     *
     * @mbg.generated
     */
//    int insert(SystemIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_icon
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int insertSelective(SystemIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_icon
     *
     * @mbg.generated
     * @param id
     * @return SystemIcon
     */
    SystemIcon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_icon
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKeySelective(SystemIcon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_icon
     *
     * @mbg.generated
     * @param record
     * @return int
     */
    int updateByPrimaryKey(SystemIcon record);
}